### ISSUE TITLE
This is my error when i run the npm run set up

### ISSUE THREAD

**Issue by Acroipeol** [atulmy/crate#10]
My Node version 8.12.0 and NPM version 6.4.1. Im windows 10 user

![image](https://user-images.githubusercontent.com/24603196/46915657-e7992f00-cfe0-11e8-99fd-54b38f79844d.png)

**Comment by atulmy** [comment]
Try downgrading `"bcrypt": "^2.0.1"` in `/code/api/package.json` and use [bash](https://gitforwindows.org/) instead of `cmd`
