### ISSUE TITLE
Invalid Date - /code/web/src/modules/admin/product/List.js

### ISSUE THREAD

**Issue by ushakrishnan** [atulmy/crate#14]
As i code displays invalid code:
![image](https://user-images.githubusercontent.com/18739265/52957162-0fb5e780-335f-11e9-9cb3-dee3bb45611e.png)

Change the code to 
`                            <td>
                              { new Date(+createdAt).toDateString() }
                            </td>
                            <td>
                              { new Date(+updatedAt).toDateString() }
                            </td>
`
**Notice the unary + before the field
shows the date as intended (of course need to format as needed)
![image](https://user-images.githubusercontent.com/18739265/52957316-64596280-335f-11e9-866d-3031044f5877.png)

As with products, same with crates too.

If the intention was different or has a better solution, respond..

Happy to do a pull request.

**Comment by atulmy** [comment]
@ushakrishnan thanks for the bug report. I've made the necessary fixes.
