### ISSUE TITLE
Realtime subscriptions implementation

### ISSUE THREAD

**Issue by gitxav** [atulmy/crate#16]
A really nice project. I love it :).
Besides that I think it would be great to implement a **realtime subscriptions** feature (notifications, chat, etc). And maybe to change accordingly the name of the Subscription model to 'Membership' or so, in order to avoid collisions between names.

Best regards.

**Comment by atulmy** [comment]
Thanks for the suggestions. If you got around building same, do send a PR.

**Comment by artem199735** [comment]
Very cool project.
It would be great if you add realtime subscription template to existing project. I am trying to add it myself, but due to lack of my knowledge on graphql, it is very difficult for me.

Cheers.

**Comment by atulmy** [comment]
@artem199735 If you can share the progress you've made on same, I can try to build upon that.
