### ISSUE TITLE
HTTP headersin GraphiQL

### ISSUE THREAD

**Issue by balarajuyogesh** [atulmy/crate#17]
Hi,

Your code base is extremely inspiring. I was experimenting on including authentication middlewares to graphql endpoint. If you have time could  you please write an article on "Securing graphiql endpoints: Authentication and Authorization" or implement the same for this project. I read many articles for the same. But none of them will be closer to your thinking.

Thank you

**Comment by atulmy** [comment]
Hi @balarajuyogesh, glad to hear you found the repository useful.

**Authentication**:
We use JWT for authentication on the backend and is handled by an Express [middleware](https://github.com/atulmy/crate/blob/master/code/api/src/setup/authentication.js). 
`crate/code/api/src/setup/authentication.js`
```javascript
// Imports
import jwt from 'jsonwebtoken'
import serverConfig from '../config/server.json'

// Authentication middleware
export default function (request, response, next) {
  let authToken = request.headers.authorization

  if (authToken && authToken !== null) {
    try {
      const token = authToken.split(' ')
      request.user = jwt.verify(token[1], serverConfig.secret)
    } catch (e) {
      console.warn('Invalid token detected.')
    }
  } else {
    request.user = {}
  }

  next()
}
```

We inject the result of the middleware into GraphQL's [context](https://github.com/atulmy/crate/blob/master/code/api/src/setup/graphql.js#L20).
`crate/code/api/src/setup/graphql.js`
```javascript
// Imports
import graphqlHTTP from 'express-graphql'

// App Imports
import serverConfig from '../config/server.json'
import authentication from './authentication'
import schema from './schema'

// Setup GraphQL
export default function (server) {
  console.info('SETUP - GraphQL...')

  server.use(authentication)

  // API (GraphQL on route `/`)
  server.use(serverConfig.graphql.endpoint, graphqlHTTP(request => ({
    schema,
    ...
    context: {
      auth: {
        user: request.user,
        isAuthenticated: request.user && request.user.id > 0
      }
    }
  })))
}
```

The context is now available in all of the resolvers. For example:
`crate/code/api/src/modules/subscription/resolvers.js`
```javascript
// Get subscription by user
export async function getByUser(parentValue, {}, { auth }) {
  if(auth.user && auth.user.id > 0) {
    return await models.Subscription.findAll({
      where: {
        userId: auth.user.id
      },
      ...
    })
  } else {
    throw new Error('Please login to view your subscriptions.')
  }
}
```

**Authorization**
To differentiate  between a `USER` or `ADMIN` or any user specific role, in case of `crate` project, we save role in `users` table:
`crate/code/api/src/modules/user/model.js`
```javascript
// User
module.exports = function(sequelize, DataTypes) {
  let User = sequelize.define('users', {
    name: {
      type: DataTypes.STRING
    },
    ...
    role: {
      type: DataTypes.TEXT
    }
  })
  ...
  return User
}
```
And use the `role` key on backend to allow/deny actions. For example:
`crate/code/api/src/modules/product/resolvers.js`
```javascript
// Create product
export async function create(parentValue, { name, ... }, { auth }) {
  if(auth.user && auth.user.role === params.user.roles.admin) {
    return await models.Product.create({
      name,
      ....
    })
  } else {
    throw new Error('Operation denied.')
  }
}
```
And also use same `role` key on frontend to hide/show menu items. For example:
`crate/code/web/src/modules/common/header/Header.js`
```jsx
<GridCell>
{
  props.user.isAuthenticated
    ? <Menu>
        { props.user.details.role === 'ADMIN' && <MenuItem to={admin.dashboard.path} section="admin">Admin</MenuItem> }
        <MenuItem to={crate.list.path}>Crates</MenuItem>
        <MenuItem to={user.subscriptions.path}>Subscriptions</MenuItem>
        <MenuItem to={user.profile.path}>Profile</MenuItem>
      </Menu>
    : <Menu>
        <MenuItem to={user.login.path}>Login</MenuItem>
        <MenuItem to={user.signup.path}>Signup</MenuItem>
      </Menu>
}
</GridCell>
```

Hope this helps.

**Comment by balarajuyogesh** [comment]
Thank you very much. This helped me a lot in understanding authentication.
