### ISSUE TITLE
How to run API end point in postman

### ISSUE THREAD

**Issue by rockers007** [atulmy/crate#18]
Hello

How to run API end point in postman ?

Thanks

**Comment by atulmy** [comment]
Hey @rockers007, follow these steps:

1. Select POST as HTTP method
2. Enter API URL http://localhost:8000 for local development or actual server URL
3. Select Body -> Raw -> JSON (application/json) as shown in below screenshot

For example:
```
{
    "query": "query ($orderBy: String) { crates (orderBy: $orderBy) { id, name, description, createdAt, updatedAt } }",
    "variables": {
        "orderBy": "ASC"
    }
}
```

<img width="1109" alt="Screenshot 2019-06-18 at 4 32 58 PM" src="https://user-images.githubusercontent.com/685786/59677249-09d5f300-91e7-11e9-8328-7d857365e973.png">

<img width="1109" alt="Screenshot 2019-06-18 at 4 36 07 PM" src="https://user-images.githubusercontent.com/685786/59677360-4275cc80-91e7-11e9-940e-239111f544e9.png">

You can also copy query from Chrome's Dev Console:

<img width="1276" alt="Screenshot 2019-06-18 at 4 36 37 PM" src="https://user-images.githubusercontent.com/685786/59677379-4d306180-91e7-11e9-9736-35173fcad6c6.png">

**Comment by rockers007** [comment]
Why do we have endpoints like http://localhost:8000/userLogin or http://localhost:8000/userSignup

**Comment by rockers007** [comment]
Thanks for your quick reply. Why don't we have endpoints like http://localhost:8000/userLogin or http://localhost:8000/userSignup ?

**Comment by atulmy** [comment]
Because we are using GraphQL. I'll recommend you to go through official GraphQL documentation here: https://graphql.org/ and the backend library used in this project: https://github.com/graphql/graphql-js/

**Comment by rockers007** [comment]
thanks
