### ISSUE TITLE
npm run setup breaks

### ISSUE THREAD

**Issue by azz0r** [atulmy/crate#2]
`GL06449M:api azz0r$ npm run setup

> api@1.0.0 setup /Users/azz0r/Downloads/crate-master/code/api
> npm run setup:install && npm run setup:db

> api@1.0.0 setup:install /Users/azz0r/Downloads/crate-master/code/api
> npm install

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

> fsevents@1.2.0 install /Users/azz0r/Downloads/crate-master/code/api/node_modules/fsevents
> node install

[fsevents] Success: "/Users/azz0r/Downloads/crate-master/code/api/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> bcrypt@2.0.1 install /Users/azz0r/Downloads/crate-master/code/api/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/Users/azz0r/Downloads/crate-master/code/api/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> nodemon@1.17.3 postinstall /Users/azz0r/Downloads/crate-master/code/api/node_modules/nodemon
> node -e "console.log('\u001b[32mLove nodemon? You can now support the project via the open collective:\u001b[22m\u001b[39m\n > \u001b[96m\u001b[1mhttps://opencollective.com/nodemon/donate\u001b[0m\n')" || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN api@1.0.0 No description
npm WARN api@1.0.0 No repository field.

added 801 packages in 206.768s

> api@1.0.0 setup:db /Users/azz0r/Downloads/crate-master/code/api
> npm run db:migrate && npm run db:seed

> api@1.0.0 db:migrate /Users/azz0r/Downloads/crate-master/code/api
> sequelize db:migrate

Sequelize CLI [Node: 8.10.0, CLI: 4.0.0, ORM: 4.37.6]

Loaded configuration file "src/config/database.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13

ERROR: connect ECONNREFUSED 127.0.0.1:3306

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@1.0.0 db:migrate: `sequelize db:migrate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api@1.0.0 db:migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by atulmy** [comment]
@azz0r seems like there is an issue with your MySQL
- if MySQL is not installed, you an download and install using this [link](https://dev.mysql.com/downloads/)
- if installed, check if MySQL process is running in your operating system
- if running, check if the port is 3306
- try connecting to MySQL using a GUI tool like [Sequel Pro](https://www.sequelpro.com/) or [MySQL Workbench](https://www.mysql.com/products/workbench/)
