### ISSUE TITLE
@babel/runtime is a production dependency not development

### ISSUE THREAD

**Issue by hosseinnedaee** [atulmy/crate#25]
Hi @atulmy
At `crate/code/api/package.json` the `@babel/runtime` installed as a devDependencies but as the [docs](https://babeljs.io/docs/en/babel-plugin-transform-runtime) say it should be installed as production dependency because it's for runtime.
If you think I'm right, I can make a PR.

**Comment by atulmy** [comment]
Yes, it seems so. Feel free to go ahead and make the PR.
