### ISSUE TITLE
        this.props.messageShow('There was some error signing you up. Please try again.')

### ISSUE THREAD

**Issue by learnwithsobhit** [atulmy/crate#27]
not able to register :(

**Comment by atulmy** [comment]
Follow the steps here to setup your backend and frontend properly: https://github.com/atulmy/crate#setup-and-running

And also make sure you have your database server running.

If issue still persists, please provide detailed log for further ispection.

**Comment by learnwithsobhit** [comment]
Thanks Atul,
it worked fine ,I missed to run API ... sorry for that.
