### ISSUE TITLE
/crate/code/mobile/ios/Pods/Target Support Files/Pods-crate/Pods-crate.debug.xcconfig: unable to open file (in target "crate" in project "crate")

### ISSUE THREAD

**Issue by dcabib** [atulmy/crate#36]
Hello,

I've just download new version on Node, React, React native and API / Web site are working fine.. But when I trying run a IOS Simulator (react-native run-ios), the simulator starts but app does not..

When I use Xcode, there is a error message:

Showing Recent Messages
/crate/code/mobile/ios/Pods/Target Support Files/Pods-crate/Pods-crate.debug.xcconfig: unable to open file (in target "crate" in project "crate")

Can you please help me?

**Comment by atulmy** [comment]
Hey @dcabib,

I just cloned a fresh copy and followed these steps:
1. Install packages `cd mobile` and `npm install`
2. Install iOS dependencies `cd mobile/ios` `pod install`
3. Run app `cd mobile` and `npx react-native run-ios` 

It worked successfully. Make sure you have latest Xcode and dependencies installed.

Also updated the readme with these steps.

**Comment by dcabib** [comment]
Great... now the APP in iOS simulator is working... thanks a lot.... 

But I still have a issue... The APP could not reach the backend server... I've restarted API, Metro Bundler and all others services... Web Application is working fine...

How can I check what is the issue with the iOS App?

**Comment by atulmy** [comment]
Check the Readme https://github.com/atulmy/crate#setup-and-running
> Modify /mobile/src/setup/config.json for API URL (tip: use ifconfig to get your local IP address)

**Comment by dcabib** [comment]
100% working fine.... Thanks a lot...
