### ISSUE TITLE
Adding apollo client issue

### ISSUE THREAD

**Issue by Grace-Endy** [atulmy/crate#38]
![React-apollo](https://user-images.githubusercontent.com/42899690/85212377-1fad5500-b320-11ea-8f90-8cf1fbec9a0a.JPG)
I tried to add the apollo client by using this way,  but It gave me an error, (Invariant violation: Could not find "client" in the context or passed in as an option.) Please,  I really need some help

**Comment by Grace-Endy** [comment]
I spent a lot of time,  google it, still can't find a solution.

**Comment by atulmy** [comment]
Please follow their official guidelines: https://www.apollographql.com/docs/react for implementation details and any issue you can check under their Github repository. This project is using [`gql-query-builder`](https://www.npmjs.com/package).
