### ISSUE TITLE
Mobile app - The icons don't display

### ISSUE THREAD

**Issue by Grace-Endy** [atulmy/crate#39]
I wonder why the icons don't display on the mobile app, neither in the navbar nor in the tabBar and so on. Any help?

**Comment by atulmy** [comment]
Can you post a screenshot?

**Comment by Grace-Endy** [comment]
![crate_screenshot](https://user-images.githubusercontent.com/42899690/85329966-1e536800-b499-11ea-94fa-036a7452ac86.jpg)

**Comment by atulmy** [comment]
Seems fine. Check if you have linked the packages properly on Android/iOS. If you are still facing issue, try to get help on official package repository: github.com/oblador/react-native-vector-icons.

<img width="350" alt="Screenshot 2020-06-25 at 2 46 33 AM" src="https://user-images.githubusercontent.com/685786/85614989-232d3d00-b68e-11ea-94e5-2be847226418.png">
