### ISSUE TITLE
Subscriptions are getting duplicated for a user

### ISSUE THREAD

**Issue by newvijay** [atulmy/crate#40]
Steps to Reproduce:
1)Navigate to crates page http://localhost:3000/crates and  click on "Subscribe" button for any item.
2) User will be navigated to subscriptions page displaying the subscribed item.
3)Go back to crates page http://localhost:3000/crates and click on "Subscribe" button again on the same item as in Step 1.
4) On the Subscriptions page, duplicate subscriptions are displayed.

Issue:
User is able to subscribe to an item many times resulting in a duplicate entry on subscriptions page.

Expected Result:
Upon subscribing for an item, button should be disabled to avoid the duplicate subscriptions.
![Screen Shot 2020-07-12 at 11 20 06 PM](https://user-images.githubusercontent.com/59512887/87267678-56e1d280-c496-11ea-9175-edf6489496aa.png)

**Comment by atulmy** [comment]
It is a design choice to allow users have multiple subscriptions to the same crate.

**Comment by newvijay** [comment]
Thank you for your response.
If I want to restrict users to have unique subscriptions, then how can I do that?

**Comment by atulmy** [comment]
In user subscription `create` function, you can check if user already has a subscription with the same crate. 

Example:
[`code/api/src/modules/subscription/resolvers.js`](https://github.com/atulmy/crate/blob/master/code/api/src/modules/subscription/resolvers.js#L43)

```javascript
export async function create(parentValue, { crateId }, { auth }) {
  if (auth.user && auth.user.id > 0) {
    const check = await models.Subscription.findOne({
      where: { id: crateId, userId: auth.user.id }
    })

    if(!check) {
      return await models.Subscription.create({
        crateId,
        userId: auth.user.id
      })
    } else {
      throw new Error('You are already subscribed to this crate.')
    }
  } else {
    throw new Error('Please login to subscribe to this crate.')
  }
}
```

**Comment by newvijay** [comment]
Thank you so much for the quick turnaround.
I tried the above solution, but it didn't worked for me.
Still it is allowing the user to subscribe more than once to the single item.

**Comment by newvijay** [comment]
I modified the above solution in the where condition as crateId Instead of Id. And it worked.
Thank you.
