### ISSUE TITLE
Issue in server

### ISSUE THREAD

**Issue by Rishita25** [atulmy/crate#41]
Hello Sir, 

How should I run the server in postman what coding should I have to do for that I am not getting 
Please tell me..

Thank You

**Comment by atulmy** [comment]
All the steps, required technology and setup are already provided in the README: https://github.com/atulmy/crate#setup-and-running

If you are new to programming, use https://stackoverflow.com to ask questions.

**Comment by Rishita25** [comment]
Thank you
