### ISSUE TITLE
npm run setup doesn't work

### ISSUE THREAD

**Issue by samarakoon-ryan** [atulmy/crate#42]
ryan (master) api
$ npm run setup

> api@1.0.0 setup /Users/ryan/Documents/Coding/Assessments/crate/code/api
> npm run setup:install && npm run setup:db

> api@1.0.0 setup:install /Users/ryan/Documents/Coding/Assessments/crate/code/api
> npm install

npm WARN api@1.0.0 No description
npm WARN api@1.0.0 No repository field.

audited 722 packages in 2.107s

29 packages are looking for funding
  run `npm fund` for details

found 271 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> api@1.0.0 setup:db /Users/ryan/Documents/Coding/Assessments/crate/code/api
> npm run db:migrate && npm run db:seed

> api@1.0.0 db:migrate /Users/ryan/Documents/Coding/Assessments/crate/code/api
> sequelize db:migrate

Sequelize CLI [Node: 12.18.3, CLI: 5.5.1, ORM: 5.21.12]

Loaded configuration file "src/config/database.json".
Using environment "development".

ERROR: Unknown database 'crate'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@1.0.0 db:migrate: `sequelize db:migrate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api@1.0.0 db:migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryan/.npm/_logs/2020-08-04T22_35_15_408Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@1.0.0 setup:db: `npm run db:migrate && npm run db:seed`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api@1.0.0 setup:db script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryan/.npm/_logs/2020-08-04T22_35_15_426Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@1.0.0 setup: `npm run setup:install && npm run setup:db`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api@1.0.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryan/.npm/_logs/2020-08-04T22_35_15_442Z-debug.log

**Comment by atulmy** [comment]
As mentioned in the [README](https://github.com/atulmy/crate#setup-and-running), before running `npm run seed`, you need to make sure you have all of the following requirements and configurations setup properly:

## Setup and Running
- Prerequisites
  - Node
  - MySQL (or Postgres / Sqlite / MSSQL)
- Clone repo `git clone git@github.com:atulmy/crate.git crate`
- Switch to `code` directory `cd code`
- Configurations
  - Modify `/api/src/config/database.json` for database credentials
  - Modify `/api/.env` for PORT (optional)
  - Modify `/web/.env` for PORT / API URL (optional)
  - Modify `/mobile/src/setup/config.json` for API URL (tip: use `ifconfig` to get your local IP address)
