### ISSUE TITLE
please check the reason for me

### ISSUE THREAD

**Issue by mericmo** [atulmy/crate#48]
npx react-native run-ios
npx: installed 611 in 187.363s
Unexpected token ?

**Comment by mericmo** [comment]
and npm run setup
Loaded configuration file "src/config/database.json".
Using environment "development".

ERROR: Unknown database 'crate'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@1.0.0 db:migrate: `sequelize db:migrate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api@1.0.0 db:migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mericmo** [comment]
npx react-native run-ios
info Found Xcode workspace "crate.xcworkspace"
xcrun: error: unable to find utility "simctl", not a developer tool or in PATH
error Could not get the simulator list from Xcode. Please open Xcode and try running project directly from there to resolve the remaining issues. Run CLI with --verbose flag for more details.

**Comment by atulmy** [comment]
Please read instructions carefully:
https://github.com/atulmy/crate#setup-and-running

**Comment by mericmo** [comment]
thx ,and i run pod install
return error:

The following build commands failed:
	CompileC /Users/freeman/Library/Developer/Xcode/DerivedData/crate-fxvyjaxnifiwnofpqriceygxipfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-Core.build/Objects-normal/x86_64/RCTCxxBridge.o /Users/freeman/project/crate/code/mobile/node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Core' from project 'Pods')
(1 failure)
