### ISSUE TITLE
Setup issue in api

### ISSUE THREAD

**Issue by VinayakBagaria** [atulmy/crate#5]
Unknown database 'crate' while running `npm run setup` in code/api.

**Comment by atulmy** [comment]
@VinayakBagaria, you need to have MySQL server running in your machine along with a database with name `crate` already created. You can solve by following below steps:

- If MySQL is not installed, you an download and install using this [link](https://dev.mysql.com/downloads/)
- If installed, check if MySQL process is running in your operating system
- If running, check if the port is 3306
- Try connecting to MySQL using a GUI tool like [Sequel Pro](https://www.sequelpro.com/) or [MySQL Workbench](https://www.mysql.com/products/workbench/) to verify
- Create a database named `crate`
- Now try running `npm run setup`

Feel free to reply if you are still facing any trouble with running the project.
