### ISSUE TITLE
The development server returned response error code: 500

### ISSUE THREAD

**Issue by fgagneten** [atulmy/crate#8]
I'm trying to run the mobile react-native application. 

After

    npm start

I tried to run the project using expo and the following error showed up:
![whatsapp image 2018-06-24 at 11 36 59](https://user-images.githubusercontent.com/14353978/41820210-3631a16e-77a4-11e8-8cb6-34c39375232d.jpeg)

Could you please tell me how can I solve the error?

Thanks

**Comment by atulmy** [comment]
Hi @fgagneten, thanks for reporting the issue. I've pushed the patch and it should now work without any issues.

The problem:
`try .. catch` missing the `error` variable in https://github.com/atulmy/crate/blob/master/code/mobile/src/modules/user/Profile/index.js#L44
```
try {
  ...
} catch(error) {
  ...
}
```
