### ISSUE TITLE
npm start  error

### ISSUE THREAD

**Issue by tomatojacky** [atulmy/crate#9]
(node:20363) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
TypeError: dep.getResourceIdentifier is not a function

**Comment by atulmy** [comment]
I'm not able to reproduce this warning. Please supply more info on which OS you are on and Node version, etc.

<img width="770" alt="screenshot 2018-09-04 at 1 56 41 pm" src="https://user-images.githubusercontent.com/685786/45019686-97769680-b04a-11e8-948c-43e8ffc41167.png">

<img width="802" alt="screenshot 2018-09-04 at 1 57 08 pm" src="https://user-images.githubusercontent.com/685786/45019688-99405a00-b04a-11e8-9f57-cf84f7bd2253.png">

<img width="730" alt="screenshot 2018-09-04 at 1 57 39 pm" src="https://user-images.githubusercontent.com/685786/45019693-9b0a1d80-b04a-11e8-96af-895c18511ce0.png">

**Comment by tomatojacky** [comment]
node V10.0.0
mac os

**Comment by atulmy** [comment]
Try with Node LTS (8.11.4).
